openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        '200':
          description: Returns Hello World message.
          content:
            application/json:
              schema:
                type: string
      summary: Get Hello World message
      tags:
        - App
  /auth/login:
    post:
      description: >-
        <p>Used for login.</p><p>Parameters: <code>username</code> - string,
        <code>password</code> - string</p>
      operationId: AuthController_postLogin
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDto'
      responses:
        '201':
          description: Returns text with token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponseDto'
        '400':
          description: >-
            When user sended something not that we expected, e.g. bad password
            or too short username
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthErrorResponseDto'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthErrorResponseDto'
        '500':
          description: Something went wrong. IDC, just not it is no so interesting
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthErrorResponseDto'
      summary: Login to account
      tags: &ref_0
        - Auth
  /auth/register:
    post:
      description: >-
        <p>Used for register.</p><p>Parameters: <code>username</code> - string,
        <code>password</code> - string, <code>email</code> - string</p>
      operationId: AuthController_postRegister
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterDto'
      responses:
        '201':
          description: Returns text with token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponseDto'
        '400':
          description: >-
            When user sended something not that we expected, e.g. bad password
            or too short username
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthErrorResponseDto'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthErrorResponseDto'
        '500':
          description: Something went wrong. IDC, just not it is not so interesting
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthErrorResponseDto'
      summary: Register account
      tags: *ref_0
info:
  title: SeaBattle API
  description: API for the SeaBattle game
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas:
    LoginDto:
      type: object
      properties:
        username:
          type: string
          description: Username for authentication
          example: john_doe
        password:
          type: string
          description: User password
          example: SecurePass123!
      required:
        - username
        - password
    AuthResponseDto:
      type: object
      properties:
        success:
          type: boolean
          description: Authentication success status
          example: true
      required:
        - success
    AuthErrorResponseDto:
      type: object
      properties:
        statusCode:
          type: number
          description: Error status code
          example: '400'
        message:
          description: Error message
          example:
            - blank_body
            - password_incorrect
          type: array
          items:
            type: string
        error:
          type: string
          description: Additional error message
          example: Unauthorized
      required:
        - statusCode
        - message
        - error
    RegisterDto:
      type: object
      properties:
        username:
          type: string
          description: Users username
          example: john_doe123
        password:
          type: string
          description: User password
          example: SecurePass123!
        email:
          type: string
          description: User email
          example: john_doe@example.com
      required:
        - username
        - password
        - email
